listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
general {
    # firefox requests sleep inhibitation by mysterious matter (such as X.com timeline extending),
    # and never release.
    ignore_wayland_inhibit = true
}
